using iText.Kernel.Pdf;
using iText.Layout;
using iText.Layout.Element;
using iText.Layout.Properties;
using ComputerSeekho.Net.Models;
using ComputerSeekho.Net.IServices;

namespace ComputerSeekho.Net.Services;

public class PdfService : IPdfService
{
    public byte[] GenerateStudentPdf(Student student)
    {
        using (var stream = new MemoryStream())
        {
            var writer = new PdfWriter(stream);
            var pdf = new PdfDocument(writer);
            var document = new Document(pdf);

            // Title
            document.Add(new Paragraph("Computer Seekho - Student Profile")
                .SetTextAlignment(TextAlignment.CENTER)
                .SetFontSize(20)
                .SetBold());

            document.Add(new Paragraph("\n")); // Spacer

            // Table
            // Table with relative column widths (1:2 ratio)
            var table = new Table(UnitValue.CreatePercentArray(new float[] { 1, 2 }))
                .SetWidth(UnitValue.CreatePercentValue(100));
            
            AddRow(table, "Field", "Details", true);
            AddRow(table, "Student Name", student.StudentName);
            AddRow(table, "Mobile", student.StudentMobile);
            AddRow(table, "Email", student.StudentEmail);
            AddRow(table, "Gender", student.StudentGender);
            AddRow(table, "Date of Birth", student.StudentDob?.ToString() ?? "N/A");
            AddRow(table, "Address", student.StudentAddress);
            AddRow(table, "Qualification", student.StudentQualification);

            if (student.Course != null)
            {
                AddRow(table, "Course Name", student.Course.CourseName);
                AddRow(table, "Course Fee", student.Course.CourseFee?.ToString());
            }

            if (student.Batch != null)
            {
                AddRow(table, "Batch Name", student.Batch.BatchName);
            }

            AddRow(table, "Payment Due", student.PaymentDue?.ToString());

            document.Add(table);

            // Footer
            document.Add(new Paragraph("\nGenerated by Computer Seekho System")
                .SetTextAlignment(TextAlignment.CENTER)
                .SetFontSize(10)
                .SetItalic());

            document.Close();
            return stream.ToArray();
        }
    }

    public byte[] GenerateReceiptPdf(Receipt receipt, Student student)
    {
        using (var stream = new MemoryStream())
        {
            var writer = new PdfWriter(stream);
            var pdf = new PdfDocument(writer);
            var document = new Document(pdf);

            document.Add(new Paragraph("Computer Seekho - Payment Receipt")
                .SetTextAlignment(TextAlignment.CENTER)
                .SetFontSize(20)
                .SetBold());

            document.Add(new Paragraph($"Receipt ID: {receipt.ReceiptId}\nDate: {receipt.ReceiptDate}"));

            var table = new Table(UnitValue.CreatePercentArray(new float[] { 1, 2 }))
                .SetWidth(UnitValue.CreatePercentValue(100));
            AddRow(table, "Student Name", student.StudentName);
            AddRow(table, "Course", student.Course?.CourseName ?? "-");
            AddRow(table, "Amount Paid", receipt.ReceiptAmount.ToString("C")); // Currency format

            document.Add(table);
            document.Close();
            return stream.ToArray();
        }
    }

    private void AddRow(Table table, string key, string? value, bool isHeader = false)
    {
        var keyCell = new Cell().Add(new Paragraph(key));
        var valCell = new Cell().Add(new Paragraph(value ?? "-"));

        if (isHeader)
        {
            keyCell.SetBold().SetBackgroundColor(iText.Kernel.Colors.ColorConstants.LIGHT_GRAY);
            valCell.SetBold().SetBackgroundColor(iText.Kernel.Colors.ColorConstants.LIGHT_GRAY);
        }

        table.AddCell(keyCell);
        table.AddCell(valCell);
    }
}
