package com.example.services;

import com.example.entities.Student;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import org.springframework.stereotype.Service;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;

@Service
public class PdfService {

    public ByteArrayInputStream generateStudentPdf(Student student) {
        Document document = new Document();
        ByteArrayOutputStream out = new ByteArrayOutputStream();

        try {
            PdfWriter.getInstance(document, out);
            document.open();

            // Title
            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 20, BaseColor.BLACK);
            Paragraph title = new Paragraph("Computer Seekho - Student Profile", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            document.add(title);
            document.add(Chunk.NEWLINE);

            // Student Info Table
            PdfPTable table = new PdfPTable(2);
            table.setWidthPercentage(100);
            table.setSpacingBefore(10f);
            table.setSpacingAfter(10f);

            // Helper to add rows
            addTableHeader(table, "Field");
            addTableHeader(table, "Details");

            addRow(table, "Student Name", student.getStudentName());
            addRow(table, "Mobile", student.getStudentMobile());
            addRow(table, "Email", student.getStudentEmail());
            addRow(table, "Gender", student.getStudentGender());
            addRow(table, "Date of Birth",
                    student.getStudentDob() != null ? student.getStudentDob().toString() : "N/A");
            addRow(table, "Address", student.getStudentAddress());
            addRow(table, "Qualification", student.getStudentQualification());

            // Course Info
            if (student.getCourse() != null) {
                addRow(table, "Course Name", student.getCourse().getCourseName());
                addRow(table, "Course Fee", String.valueOf(student.getCourse().getCourseFee()));
            }

            if (student.getBatch() != null) {
                addRow(table, "Batch Name", student.getBatch().getBatchName());
                // addRow(table, "Batch Time", student.getBatch().getBatchTime());
            }

            // Payment Info
            addRow(table, "Payment Due", String.valueOf(student.getPaymentDue()));

            document.add(table);

            // Footer
            Font footerFont = FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 10, BaseColor.GRAY);
            Paragraph footer = new Paragraph("Generated by Computer Seekho System", footerFont);
            footer.setAlignment(Element.ALIGN_CENTER);
            document.add(footer);

            document.close();

        } catch (DocumentException e) {
            e.printStackTrace();
        }

        return new ByteArrayInputStream(out.toByteArray());
    }

    private void addTableHeader(PdfPTable table, String headerTitle) {
        PdfPCell header = new PdfPCell();
        header.setBackgroundColor(BaseColor.LIGHT_GRAY);
        header.setPadding(5);
        header.setPhrase(new Phrase(headerTitle));
        table.addCell(header);
    }

    private void addRow(PdfPTable table, String key, String value) {
        table.addCell(key);
        table.addCell(value == null ? "-" : value);
    }
}
